set(_CATKIN_CURRENT_PACKAGE "amr_mapping")
set(amr_mapping_VERSION "1.0.0")
set(amr_mapping_MAINTAINER "Alexander Hagg <alexander.hagg@inf.h-brs.de>")
set(amr_mapping_PACKAGE_FORMAT "1")
set(amr_mapping_BUILD_DEPENDS "roscpp" "nav_msgs" "tf" "amr_msgs" "amr_srvs" "amr_stage")
set(amr_mapping_BUILD_EXPORT_DEPENDS "roscpp" "nav_msgs" "tf" "amr_msgs" "amr_srvs" "amr_stage")
set(amr_mapping_BUILDTOOL_DEPENDS "catkin")
set(amr_mapping_BUILDTOOL_EXPORT_DEPENDS )
set(amr_mapping_EXEC_DEPENDS "roscpp" "nav_msgs" "tf" "amr_msgs" "amr_srvs" "amr_stage")
set(amr_mapping_RUN_DEPENDS "roscpp" "nav_msgs" "tf" "amr_msgs" "amr_srvs" "amr_stage")
set(amr_mapping_TEST_DEPENDS )
set(amr_mapping_DOC_DEPENDS )
set(amr_mapping_DEPRECATED "")