set(_CATKIN_CURRENT_PACKAGE "amr_bugs")
set(amr_bugs_VERSION "1.0.0")
set(amr_bugs_MAINTAINER "Alexander Hagg <alexander.hagg@inf.h-brs.de>")
set(amr_bugs_PACKAGE_FORMAT "1")
set(amr_bugs_BUILD_DEPENDS "roscpp" "rospy" "smach" "smach_ros" "smach_viewer" "dynamic_reconfigure" "actionlib" "tf" "std_srvs" "geometry_msgs" "amr_msgs" "amr_srvs" "amr_stage" "amr_perception" "amr_navigation")
set(amr_bugs_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "smach" "smach_ros" "smach_viewer" "dynamic_reconfigure" "actionlib" "tf" "std_srvs" "geometry_msgs" "amr_msgs" "amr_srvs" "amr_stage" "amr_perception" "amr_navigation")
set(amr_bugs_BUILDTOOL_DEPENDS "catkin")
set(amr_bugs_BUILDTOOL_EXPORT_DEPENDS )
set(amr_bugs_EXEC_DEPENDS "roscpp" "rospy" "smach" "smach_ros" "smach_viewer" "dynamic_reconfigure" "actionlib" "tf" "std_srvs" "geometry_msgs" "amr_msgs" "amr_srvs" "amr_stage" "amr_perception" "amr_navigation")
set(amr_bugs_RUN_DEPENDS "roscpp" "rospy" "smach" "smach_ros" "smach_viewer" "dynamic_reconfigure" "actionlib" "tf" "std_srvs" "geometry_msgs" "amr_msgs" "amr_srvs" "amr_stage" "amr_perception" "amr_navigation")
set(amr_bugs_TEST_DEPENDS )
set(amr_bugs_DOC_DEPENDS )
set(amr_bugs_DEPRECATED "")