set(_CATKIN_CURRENT_PACKAGE "amr_localization")
set(amr_localization_VERSION "1.0.0")
set(amr_localization_MAINTAINER "Alexander Hagg <alexander.hagg@inf.h-brs.de>")
set(amr_localization_PACKAGE_FORMAT "1")
set(amr_localization_BUILD_DEPENDS "roscpp" "rospy" "tf" "visualization_msgs" "amr_msgs" "amr_srvs" "amr_stage" "amr_mapping")
set(amr_localization_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "tf" "visualization_msgs" "amr_msgs" "amr_srvs" "amr_stage" "amr_mapping")
set(amr_localization_BUILDTOOL_DEPENDS "catkin")
set(amr_localization_BUILDTOOL_EXPORT_DEPENDS )
set(amr_localization_EXEC_DEPENDS "roscpp" "rospy" "tf" "visualization_msgs" "amr_msgs" "amr_srvs" "amr_stage" "amr_mapping")
set(amr_localization_RUN_DEPENDS "roscpp" "rospy" "tf" "visualization_msgs" "amr_msgs" "amr_srvs" "amr_stage" "amr_mapping")
set(amr_localization_TEST_DEPENDS )
set(amr_localization_DOC_DEPENDS )
set(amr_localization_DEPRECATED "")