set(_CATKIN_CURRENT_PACKAGE "amr_navigation")
set(amr_navigation_VERSION "1.0.0")
set(amr_navigation_MAINTAINER "Alexander Hagg <alexander.hagg@inf.h-brs.de>")
set(amr_navigation_PACKAGE_FORMAT "1")
set(amr_navigation_BUILD_DEPENDS "roscpp" "actionlib" "tf" "amr_msgs" "amr_srvs" "amr_stage")
set(amr_navigation_BUILD_EXPORT_DEPENDS "roscpp" "actionlib" "tf" "amr_msgs" "amr_srvs" "amr_stage")
set(amr_navigation_BUILDTOOL_DEPENDS "catkin")
set(amr_navigation_BUILDTOOL_EXPORT_DEPENDS )
set(amr_navigation_EXEC_DEPENDS "roscpp" "actionlib" "tf" "amr_msgs" "amr_srvs" "amr_stage")
set(amr_navigation_RUN_DEPENDS "roscpp" "actionlib" "tf" "amr_msgs" "amr_srvs" "amr_stage")
set(amr_navigation_TEST_DEPENDS )
set(amr_navigation_DOC_DEPENDS )
set(amr_navigation_DEPRECATED "")