set(amr_navigation_SETUP_PY_VERSION "1.0.0")
set(amr_navigation_SETUP_PY_SCRIPTS "")
set(amr_navigation_SETUP_PY_PACKAGES "amr_navigation")
set(amr_navigation_SETUP_PY_PACKAGE_DIRS "src/amr_navigation")
set(amr_navigation_SETUP_PY_MODULES "")
set(amr_navigation_SETUP_PY_MODULE_DIRS "")